trigger:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - 'UITests/*'

pr:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - 'UITests/*'

variables:
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: Build
  pool:
    vmImage: windows-2019

  strategy:
    matrix:
      Channel_CD_Web:
        ChannelName: CD-Web
        DistributionUrl: https://mywpfapp.azurewebsites.net/CD
        MsixPackageId: MyWPFApp.DevOpsDemo.CD
        MsixPublisherId: CN=build
        MsixPackageDisplayName: MyWPFApp (CD)
        MsixBuildMode: SideLoadOnly
        MsixGenerateAppInstaller: true

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 5.0.x'
    inputs:
      version: 5.0.x

  - task: MSBuild@1
    displayName: Build for $(BuildConfiguration)
    inputs:
      solution: MyWPFApp.sln
      platform: x64
      msbuildArguments: /restore /p:AppInstallerUri=$(DistributionUrl) /p:UapAppxPackageBuildMode=$(MsixBuildMode) /p:GenerateAppInstallerFile=$(MsixGenerateAppInstaller)
      configuration: $(BuildConfiguration)
      maximumCpuCount: false

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: $(ChannelName)
      targetPath: MyWPFApp.Package/AppPackages
