trigger:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - 'UITests/*'

pr:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - 'UITests/*'

variables:
  buildConfiguration: Release
  buildPlatform: x64
  distributionUrl: X:\PackageTesting
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages'
  msixPackageId: MyWPFApp.DevOpsDemo.CD
  msixPublisherId: CN=build
  msixPackageDisplayName: MyWPFApp (CD)
  msixBuildMode: SideLoadOnly
  msixGenerateAppInstaller: true

jobs:
- job: Build
  pool:
    vmImage: windows-latest

  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK
    inputs:
      version: 8.0.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: .NET Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: select

  - task: VSBuild@1
    displayName: 'Build for $(buildConfiguration)'
    inputs:
      solution: '*.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: >
        /p:AppInstallerUri=$(distributionUrl)
        /p:UapAppxPackageBuildMode=$(msixBuildMode)
        /p:GenerateAppInstallerFile=$(msixGenerateAppInstaller)
      maximumCpuCount: false

  - task: CopyFiles@2
    displayName: Copy files
    inputs:
      SourceFolder: '$(appxPackageDir)'
      Contents: |
        **\*.msixbundle
        *.appinstaller
      TargetFolder: MyWPFApp.Package/Bundle

  - task: PublishPipelineArtifact@0
    displayName: Publish files
    inputs:
      artifactName: drop
      targetPath: MyWPFApp.Package/Bundle
